name: freebsd_build

on: [push]

jobs:
  build:
    runs-on: macos-latest
    name: A job to run test FreeBSD
    # env:
    steps:
    - uses: actions/checkout@v2
    - name: Build in FreeBSD
      id: test
      uses: vmactions/freebsd-vm@v0.0.9
      with:
        # envs: 'MYTOKEN MYTOKEN2'
        usesh: true
        prepare: pkg install -y curl libevent gmake 
        run: |
          pwd
          freebsd-version
          gmake DISABLE_SHADOWSOCKS=1
